@startuml
actor User
participant InputHandler as ":InputHandler"
participant InputParser as ":InputParser"
participant BookList as ":BookList"
participant Book as ":Book"
participant Formatter as ":Formatter"
participant Storage as ":Storage"

User -> InputHandler: userInputLine
activate InputHandler

InputHandler -> InputParser: extractCommandArgs(userInputLine)
activate InputParser

InputParser --> InputHandler: commandArgs[]
deactivate InputParser

alt commandArgs[0] == add-book
    InputHandler -> InputHandler : addBook()
    activate InputHandler

    opt commandArgs.length < 2
        note right
        rest of sequence is cancelled in error cases denoted in opt frames
        end note
        InputHandler -> Formatter: Print exception message
        activate Formatter
        Formatter --> InputHandler
        deactivate Formatter
    end

    InputHandler -> InputParser: extractAddBookArgs(commandArgs[1])
    activate InputParser

    InputParser --> InputHandler: parsedArgs
    deactivate InputParser

    InputHandler -> BookList: findBookByTitle(BOOK_TITLE)
    activate BookList

    BookList --> InputHandler: Book
    deactivate BookList

    opt Book != null
        InputHandler -> Formatter: Print exception message
        activate Formatter
        Formatter --> InputHandler
        deactivate Formatter
    end

    InputHandler -> Book ** : Book(parsedArgs)
    activate Book

    Book --> InputHandler : newBook
    deactivate Book

    InputHandler -> BookList: addBook(newBook)
    activate BookList


    BookList --> InputHandler: Book added
    deactivate BookList

    InputHandler -> Formatter: printBorderedMessage("New book added: {BOOK_TITLE}")
    activate Formatter

    Formatter --> InputHandler
    deactivate Formatter

    InputHandler -> Storage: saveInventory(bookList)
    activate Storage

    Storage --> InputHandler
    deactivate Storage

InputHandler --> InputHandler
deactivate InputHandler

else else
    note over InputHandler : other commands
end

InputHandler --> User
deactivate InputHandler
@enduml