@startuml
actor User
participant InputHandler
participant InputParser
participant BookList
participant LoanList
participant Formatter
participant Storage

User -> InputHandler: "add-loan BOOK_TITLE n/BORROWER_NAME d/RETURN_DATE p/PHONE_NUMBER e/EMAIL"
activate InputHandler

InputHandler -> InputParser: extractCommandArgs(userInputLine)
activate InputParser

InputParser --> InputHandler: commandArgs[]
deactivate InputParser

alt commandArgs[0] == add-loan
    InputHandler -> InputHandler : addLoan()
    activate InputHandler

alt commandArgs.length >= 2
    InputHandler -> InputParser: extractAddLoanArgs(commandArgs[1])
    activate InputParser

    InputParser --> InputHandler: parsedArgs [BOOK_TITLE, BORROWER_NAME, RETURN_DATE, PHONE_NUMBER, EMAIL]
    deactivate InputParser

    InputHandler -> BookList: findBookByTitle(BOOK_TITLE)
    activate BookList

    BookList --> InputHandler: Book or null
    deactivate BookList

    alt Book != null
        InputHandler -> Book: getOnLoan()
        activate Book

        Book --> InputHandler
        deactivate Book

        alt loanedBook.getOnLoan() == false
            InputHandler -> LoanList: addLoan(new Loan(Book, BORROWER_NAME, RETURN_DATE, PHONE_NUMBER, EMAIL))
            activate LoanList
            LoanList --> InputHandler: Loan added
            deactivate LoanList

            InputHandler -> Book: setOnLoan(true)
            activate Book

            Book --> InputHandler
            deactivate Book

            InputHandler -> Formatter: printBorderedMessage("Loan added successfully")
            activate Formatter

            Formatter --> InputHandler
            deactivate Formatter

            InputHandler -> Storage: saveLoans(loanList)
            activate Storage

            Storage --> InputHandler
            deactivate Storage

            InputHandler -> Storage: saveInventory(bookList)
            activate Storage

            Storage --> InputHandler
            deactivate Storage

        else
            InputHandler -> Formatter: printBorderedMessage("The book is currently out on loan")
            activate Formatter

            Formatter --> InputHandler
            deactivate Formatter
        end
    else
        InputHandler -> Formatter: printBorderedMessage("Book not found in inventory")
        activate Formatter

        Formatter --> InputHandler
        deactivate Formatter
    end

    else
        InputHandler -> Formatter: printBorderedMessage("Invalid format for add-loan")
        activate Formatter
        Formatter --> InputHandler
        deactivate Formatter
    end

InputHandler --> InputHandler
deactivate InputHandler

else
    note over InputHandler : other commands
end

deactivate InputHandler
InputHandler --> User
@enduml