@startuml 
autoactivate on
actor User
participant InputHandler as ":InputHandler"
participant InputParser as ":InputParser"
participant Book as ":Book"
participant BookList as ":BookList"
participant LoanList as ":LoanList"
participant Formatter as ":Formatter"
participant Storage as ":Storage"
User -> InputHandler : userInputLine
    InputHandler -> InputParser : extractCommandArgs(userInputLine)
    return commandArgs
alt commandArgs[0] == delete-loan
    InputHandler -> InputHandler : deleteLoan()
    InputHandler -> InputParser : extractDeleteLoanArgs()
    return deleteLoanArgs 
    InputHandler -> BookList : findBookByTitle()
    return loanedBook 
    InputHandler -> LoanList : findLoan(loanedBook)
    return loan

    opt No book with provided title OR Book not on loan OR Loan does not exist
        note right
        rest of sequence is cancelled in
        error cases denoted in opt frame
        end note
        InputHandler -> Formatter : Print exception message
        return
    end

    InputHandler -> LoanList : deleteLoan(loan)
    return
    InputHandler -> Book : setOnLoan(true)
    return
    InputHandler -> Formatter : printBorderedMessage(Success Message)
    return
    InputHandler -> Storage : saveLoans(loanList)
    return
    InputHandler -> Storage : saveInventory(bookList)
    return

    return

else else
    note over InputHandler : other commands
end
return
@enduml
    