@startuml
actor User
participant InputHandler as ":InputHandler"
participant InputParser as ":InputParser"
participant BookList as ":BookList"
participant LoanList as ":LoanList"
participant Formatter as ":Formatter"
participant Storage as ":Storage"

User -> InputHandler: "remove-book BOOK_TITLE"
activate InputHandler

    InputHandler -> InputParser: extractCommandArgs(userInputLine)
    activate InputParser
    InputParser --> InputHandler: commandArgs[]
    deactivate InputParser
    alt commandArgs[0] == "remove-book"
        InputHandler -> InputHandler: removeBook(commandArgs)
        activate InputHandler
        InputHandler -> BookList: findBookByTitle(bookTitle)
        activate BookList
        BookList --> InputHandler: toRemove
        deactivate BookList
        alt toRemove == null
            InputHandler -> Formatter: printBorderedMessage("Book not found in inventory: {BOOK_TITLE}")
            activate Formatter
            Formatter --> InputHandler
            deactivate Formatter
        else else
            InputHandler -> LoanList: removeLoansByBook(toRemove)
            activate LoanList
            LoanList --> InputHandler
            deactivate LoanList

            InputHandler -> BookList: removeBook(toRemove)
            activate BookList
            BookList --> InputHandler
            deactivate BookList
            InputHandler -> Storage: saveInventory(bookList)
            activate Storage
            Storage --> InputHandler
            deactivate Storage
            InputHandler -> Formatter: printBorderedMessage("Removed book: {BOOK_TITLE}")
            activate Formatter
            Formatter --> InputHandler
            deactivate Formatter
            end
            InputHandler --> InputHandler
            deactivate InputHandler

    else else
    note over InputHandler
    other command cases
    end note
    end

InputHandler --> User
deactivate InputHandler
@enduml
