@startuml

participant InputHandler as ":InputHandler"
participant Storage as ":Storage"
participant BookList as ":BookList"
participant File as ":File"
participant FileWriter as ":FileWriter"
participant Book as ":Book"
participant Formatter as ":Formatter"

activate InputHandler

InputHandler -> Storage: saveInventory(bookList)
activate Storage

' Check if directory exists
Storage -> File ** : new File(FOLDER_PATH)
activate File
File --> Storage: directory
deactivate File
alt Directory does not exist
    Storage -> File: mkdirs()
    activate File
    File --> Storage: 
    deactivate File
end

deactivate File

' Create FileWriter for INVENTORY_FILE_PATH
Storage -> FileWriter ** : new FileWriter(INVENTORY_FILE_PATH)
activate FileWriter



FileWriter --> Storage: fileWriter
deactivate FileWriter

' Retrieve list of books from BookList
Storage -> BookList: getBookList()
activate BookList
BookList --> Storage: List<Book>
deactivate BookList

' Loop through each Book and write its file string
loop for each book in BookList
    Storage -> Book: toFileString()
    activate Book
    Book --> Storage: fileString
    deactivate Book
    Storage -> FileWriter: write(fileString + lineSeparator)
    activate FileWriter
    FileWriter --> Storage:
    deactivate FileWriter
end

' Close the FileWriter
Storage -> FileWriter: close()
activate FileWriter

FileWriter --> Storage
deactivate FileWriter 

destroy FileWriter
Storage --> InputHandler 
deactivate Storage

destroy File

@enduml