@startuml
actor User
participant InputHandler
participant InputParser
participant LoanList
participant Formatter
participant Loan


User -> InputHandler: "view-loans"
activate InputHandler
    activate InputHandler
    InputHandler -> InputParser: extractCommandArgs(userInputLine)
    activate InputParser
    InputParser --> InputHandler: commandArgs[]
    deactivate InputParser
    alt commandArgs[0] == "view-loans"
        InputHandler -> LoanList: viewLoanList()
        activate LoanList
        alt LoanList.isEmpty() 
            LoanList -> Formatter : printBorderedMessage("Loan List Empty!")
            activate Formatter
            Formatter --> LoanList
            deactivate Formatter
            LoanList --> InputHandler
        else
            activate Formatter
            LoanList -> Formatter: printLoanList(LoanList)
                loop for each Loan
                    Formatter -> Loan: toString()
                    activate Loan
                    Loan --> Formatter: Loan info
                    deactivate Loan
                end
            Formatter --> LoanList
            deactivate Formatter
        LoanList --> InputHandler
        deactivate LoanList
        end
    else
    note over InputHandler
    other command cases
    end note
end
deactivate InputHandler

@enduml
