@startuml
actor User
participant InputHandler as ":InputHandler"
participant InputParser as ":InputParser"
participant BookList as ":BookList"
participant Formatter as ":Formatter"
participant Book as ":Book"


User -> InputHandler: "view-inventory"
activate InputHandler
    InputHandler -> InputParser: extractCommandArgs(userInputLine)
    activate InputParser
    InputParser --> InputHandler: commandArgs[]
    deactivate InputParser
    alt commandArgs[0] == "view-inventory"
        InputHandler -> BookList: viewBookList()
        activate BookList
        alt BookList.isEmpty() 
            BookList -> Formatter : printBorderedMessage("Book List Empty!")
            activate Formatter
            Formatter --> BookList
            deactivate Formatter
            BookList --> InputHandler
        else else
            BookList -> Formatter: printBookList(bookList)
            activate Formatter
                loop for each Book
                    Formatter -> Book: toString()
                    activate Book
                    Book --> Formatter: Book info
                    deactivate Book
                end
            Formatter --> BookList
            deactivate Formatter
        BookList --> InputHandler
        deactivate BookList
        end
    else else
    note over InputHandler
    other command cases
    end note
end
InputHandler --> User
deactivate InputHandler

@enduml
